# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddField(
            model_name='tag',
            name='linked_posts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='post.Post'),
        ),
    ]
